name: codit_competition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  lottie: ^3.3.1
  supabase: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Background.json
    - assets/backgroundGreen.json
    - assets/2ndBackground.json
    - assets/Confetti.json
    - assets/ComputerScience2.json
    - assets/Business.json
    - assets/Background_shooting_star.json
    - assets/CodeIt.jpg
    - assets/MUBC.jpg
    - assets/BackgroundColoredGreen.json
    - assets/darkgradient.json
    - assets/wavyLines.json
    - assets/CSvsBusiness.png